### ISSUE TITLE
Potential bug in add_event: Invalid payer makes funds disappear

### ISSUE THREAD

**Issue by TSchattschneider** [nagua/abrechnung#17]
AFAIK, if you provide a random non-existing account string as payer to add_event, the costs will be deducted from all the participants' accounts but they will not get added anywhere.

**Comment by nagua** [comment]
In the current way the program is written, the telegram interface does not allow for a payer, that is not also a participant. And the add_event function checks if all participants were found.

**Comment by lassepe** [comment]
This can be closed.
